// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ProductType string

const (
	ProductTypePhysical ProductType = "physical"
	ProductTypeService  ProductType = "service"
)

func (e *ProductType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductType(s)
	case string:
		*e = ProductType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductType: %T", src)
	}
	return nil
}

type NullProductType struct {
	ProductType ProductType `json:"product_type"`
	Valid       bool        `json:"valid"` // Valid is true if ProductType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductType) Scan(value interface{}) error {
	if value == nil {
		ns.ProductType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductType), nil
}

type ActivityLog struct {
	ID         uuid.UUID             `json:"id"`
	EntityType string                `json:"entity_type"`
	EntityID   uuid.UUID             `json:"entity_id"`
	Action     string                `json:"action"`
	Changes    pqtype.NullRawMessage `json:"changes"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UserID     uuid.NullUUID         `json:"user_id"`
}

type Branch struct {
	ID             uuid.UUID      `json:"id"`
	Name           string         `json:"name"`
	Address        sql.NullString `json:"address"`
	IsDefault      sql.NullBool   `json:"is_default"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Category struct {
	ID          uuid.UUID      `json:"id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Name        string         `json:"name"`
	BranchID    uuid.UUID      `json:"branch_id"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Currency struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Symbol    sql.NullString `json:"symbol"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Customer struct {
	ID             uuid.UUID             `json:"id"`
	Name           string                `json:"name"`
	Email          sql.NullString        `json:"email"`
	Phone          sql.NullString        `json:"phone"`
	BillingAddress pqtype.NullRawMessage `json:"billing_address"`
	CreatedAt      sql.NullTime          `json:"created_at"`
}

type Inventory struct {
	ID          uuid.UUID      `json:"id"`
	VersionID   uuid.UUID      `json:"version_id"`
	BranchID    uuid.UUID      `json:"branch_id"`
	Quantity    sql.NullInt32  `json:"quantity"`
	UnitCost    sql.NullString `json:"unit_cost"`
	LastCounted sql.NullTime   `json:"last_counted"`
}

type Invoice struct {
	ID            uuid.UUID             `json:"id"`
	CustomerID    uuid.NullUUID         `json:"customer_id"`
	InvoiceNumber string                `json:"invoice_number"`
	Subtotal      string                `json:"subtotal"`
	Discount      string                `json:"discount"`
	Total         string                `json:"total"`
	Status        string                `json:"status"`
	CreatedBy     uuid.NullUUID         `json:"created_by"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	CurrencyID    uuid.NullUUID         `json:"currency_id"`
	DueDate       sql.NullTime          `json:"due_date"`
	Reminders     pqtype.NullRawMessage `json:"reminders"`
	Metadata      pqtype.NullRawMessage `json:"metadata"`
	AmountPaid    string                `json:"amount_paid"`
	BalanceDue    sql.NullString        `json:"balance_due"`
}

type InvoiceItem struct {
	ID        uuid.UUID             `json:"id"`
	InvoiceID uuid.UUID             `json:"invoice_id"`
	VersionID uuid.UUID             `json:"version_id"`
	Quantity  int32                 `json:"quantity"`
	UnitPrice string                `json:"unit_price"`
	Subtotal  string                `json:"subtotal"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

type Organization struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Active    sql.NullBool `json:"active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Payment struct {
	ID            uuid.UUID             `json:"id"`
	InvoiceID     uuid.NullUUID         `json:"invoice_id"`
	PaymentMethod sql.NullString        `json:"payment_method"`
	PaymentAmount string                `json:"payment_amount"`
	PaymentRef    sql.NullString        `json:"payment_ref"`
	PaymentDate   time.Time             `json:"payment_date"`
	Metadata      pqtype.NullRawMessage `json:"metadata"`
	CreatedAt     time.Time             `json:"created_at"`
	CreatedBy     uuid.UUID             `json:"created_by"`
}

type PaymentInfo struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.NullUUID  `json:"user_id"`
	AccountNo   sql.NullString `json:"account_no"`
	RoutingNo   sql.NullString `json:"routing_no"`
	AccountName sql.NullString `json:"account_name"`
	BankName    sql.NullString `json:"bank_name"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Product struct {
	ID                  uuid.UUID             `json:"id"`
	CategoryID          uuid.NullUUID         `json:"category_id"`
	BranchID            uuid.UUID             `json:"branch_id"`
	Name                string                `json:"name"`
	ProductType         string                `json:"product_type"`
	ServicePricingModel sql.NullString        `json:"service_pricing_model"`
	DefaultUnit         sql.NullString        `json:"default_unit"`
	IsBillable          sql.NullBool          `json:"is_billable"`
	Sku                 sql.NullString        `json:"sku"`
	Description         sql.NullString        `json:"description"`
	BasePrice           sql.NullString        `json:"base_price"`
	CustomFields        pqtype.NullRawMessage `json:"custom_fields"`
	CreatedAt           sql.NullTime          `json:"created_at"`
	UpdatedAt           sql.NullTime          `json:"updated_at"`
}

type ProductVersion struct {
	ID              uuid.UUID             `json:"id"`
	ProductID       uuid.UUID             `json:"product_id"`
	BranchID        uuid.UUID             `json:"branch_id"`
	Sku             sql.NullString        `json:"sku"`
	Name            string                `json:"name"`
	PriceAdjustment sql.NullString        `json:"price_adjustment"`
	Attributes      pqtype.NullRawMessage `json:"attributes"`
	StockQuantity   sql.NullInt32         `json:"stock_quantity"`
	ReorderPoint    sql.NullInt32         `json:"reorder_point"`
	CreatedAt       sql.NullTime          `json:"created_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Name      sql.NullString `json:"name"`
	Email     string         `json:"email"`
	Address   sql.NullString `json:"address"`
	BranchID  uuid.UUID      `json:"branch_id"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
