// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: product_versions.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createProductVersion = `-- name: CreateProductVersion :one
INSERT INTO product_versions (
    id, product_id, branch_id, sku, name, 
    price_adjustment, attributes, stock_quantity, reorder_point
) VALUES (
    uuid_generate_v4(), $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, product_id, branch_id, sku, name, price_adjustment, attributes, stock_quantity, reorder_point, created_at
`

type CreateProductVersionParams struct {
	ProductID       uuid.UUID             `json:"product_id"`
	BranchID        uuid.UUID             `json:"branch_id"`
	Sku             sql.NullString        `json:"sku"`
	Name            string                `json:"name"`
	PriceAdjustment sql.NullString        `json:"price_adjustment"`
	Attributes      pqtype.NullRawMessage `json:"attributes"`
	StockQuantity   sql.NullInt32         `json:"stock_quantity"`
	ReorderPoint    sql.NullInt32         `json:"reorder_point"`
}

func (q *Queries) CreateProductVersion(ctx context.Context, arg CreateProductVersionParams) (ProductVersion, error) {
	row := q.db.QueryRowContext(ctx, createProductVersion,
		arg.ProductID,
		arg.BranchID,
		arg.Sku,
		arg.Name,
		arg.PriceAdjustment,
		arg.Attributes,
		arg.StockQuantity,
		arg.ReorderPoint,
	)
	var i ProductVersion
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.Sku,
		&i.Name,
		&i.PriceAdjustment,
		&i.Attributes,
		&i.StockQuantity,
		&i.ReorderPoint,
		&i.CreatedAt,
	)
	return i, err
}

const getProductVersionsByProductID = `-- name: GetProductVersionsByProductID :many
SELECT id, product_id, branch_id, sku, name, price_adjustment, attributes, stock_quantity, reorder_point, created_at FROM product_versions WHERE product_id = $1
`

func (q *Queries) GetProductVersionsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductVersion, error) {
	rows, err := q.db.QueryContext(ctx, getProductVersionsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVersion{}
	for rows.Next() {
		var i ProductVersion
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BranchID,
			&i.Sku,
			&i.Name,
			&i.PriceAdjustment,
			&i.Attributes,
			&i.StockQuantity,
			&i.ReorderPoint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductVersion = `-- name: UpdateProductVersion :one
UPDATE product_versions 
SET 
    sku = $2, 
    name = $3, 
    price_adjustment = $4,
    attributes = $5,
    stock_quantity = $6,
    reorder_point = $7
WHERE id = $1 
RETURNING id, product_id, branch_id, sku, name, price_adjustment, attributes, stock_quantity, reorder_point, created_at
`

type UpdateProductVersionParams struct {
	ID              uuid.UUID             `json:"id"`
	Sku             sql.NullString        `json:"sku"`
	Name            string                `json:"name"`
	PriceAdjustment sql.NullString        `json:"price_adjustment"`
	Attributes      pqtype.NullRawMessage `json:"attributes"`
	StockQuantity   sql.NullInt32         `json:"stock_quantity"`
	ReorderPoint    sql.NullInt32         `json:"reorder_point"`
}

func (q *Queries) UpdateProductVersion(ctx context.Context, arg UpdateProductVersionParams) (ProductVersion, error) {
	row := q.db.QueryRowContext(ctx, updateProductVersion,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.PriceAdjustment,
		arg.Attributes,
		arg.StockQuantity,
		arg.ReorderPoint,
	)
	var i ProductVersion
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.Sku,
		&i.Name,
		&i.PriceAdjustment,
		&i.Attributes,
		&i.StockQuantity,
		&i.ReorderPoint,
		&i.CreatedAt,
	)
	return i, err
}
